### ISSUE TITLE
Обрабатывай код ответа, если бросилось NotFoundEx, а не флаг в мапе

### ISSUE THREAD

**Issue by sboriskin287** [wwwAiru/Graduation_Work#10]
https://github.com/wwwAiru/Graduation_Work/blob/e1bc6b96267b4d98735d50bd91e207af2f75c25a/src/main/java/com/golikov/bank/domain/product/InvestProductRestController.java#L51

**Comment by wwwAiru** [comment]
https://github.com/wwwAiru/Graduation_Work/commit/9121837971e98cb896eb8629ec517ffbb5340674
переделал
