### ISSUE TITLE
Currency сделай бином CurrencyHolder в котором объявлена мапа и @PostConstruct вынеси туда

### ISSUE THREAD

**Issue by sboriskin287** [wwwAiru/Graduation_Work#11]
https://github.com/wwwAiru/Graduation_Work/blob/af332ab2e6a792778e07422a1b03a38517843ab5/src/main/java/com/golikov/bank/domain/currency/CurrencyService.java#L33

**Comment by wwwAiru** [comment]
https://github.com/wwwAiru/Graduation_Work/commit/0f7b75339dc5dbdc1a731897e336e4bb0e091fab
Переделал
