### ISSUE TITLE
Немного съехали параметры

### ISSUE THREAD

**Issue by sboriskin287** [wwwAiru/Graduation_Work#6]
https://github.com/wwwAiru/Graduation_Work/blob/e1bc6b96267b4d98735d50bd91e207af2f75c25a/src/main/java/com/golikov/bank/exception/GlobalExceptionHandler.java#L38

**Comment by wwwAiru** [comment]
пофиксил https://github.com/wwwAiru/Graduation_Work/commit/0a125107d632ef98c89bdd21b8f9f7b3554d28f6
